### ISSUE TITLE
Not working for audio calls between two machines running OSX

### ISSUE THREAD

**Issue by markNZed** [cyph/cyph#56] opened 2018-02-28 15:37 UTC
On one machine we have sound and on the other no sound. On the machine with no sound there is a spinning circle. We can send video from the machine with no sound to the other machine. Text messages work in both directions.

**Comment by buu700** [comment] 2018-03-06 01:59
Thanks for the report! We'll do some testing to see if we can reproduce the problem at all, and we're looking into a potential performance/reliability improvement for voice/video calling that may help mitigate this general type of issue.

**Comment by buu700** [comment] 2018-06-24 22:31
Hey, any idea if this is still an issue? A number of improvements and edge case fixes have been put in since this ticket was opened, so I'll go ahead and close this for now until it happens again.

**Closed by buu700** 2018-06-24 22:31 UTC
